from pathlib import Path
from typing import Final, List, TextIO, Any
import json
from datetime import datetime

NAMESPACE: Final[str] = "mc"


def remove_built_files(build_folder_path: Path):
    for path in build_folder_path.joinpath("include/gen").glob("*.h"):
        path.unlink(missing_ok=True)
    for path in build_folder_path.joinpath("src").glob("*.cpp"):
        path.unlink(missing_ok=True)


def write_source_heading(source: TextIO):
    source.write(f"// Generated by `graphics_data_writer.py` in {datetime.now()}\n")
    source.write("//\n")
    source.write("// DO NOT edit this file directly - changes will be overwritten!\n\n")


def write_sprite_datas_sources(
    sprites_folder_path: Path, build_folder_path: Path, tools_mtime: float
):
    build_include_path = build_folder_path.joinpath("include/gen")
    # build_src_path = build_folder_path.joinpath("src")

    sprite_names: List[str] = []
    sprite_kind_enum_regen = False

    for json_path in sorted(sprites_folder_path.rglob("*.json")):
        name: str = json_path.stem
        datas_header_path: Path = build_include_path.joinpath(
            f"spr_{name}"
        ).with_suffix(".h")

        json_obj: Any = None
        with open(json_path, "r", encoding="utf-8") as json_file:
            json_obj = json.load(json_file)

        collisions: Any = []
        if "mcedit" in json_obj and "collisions" in json_obj["mcedit"]:
            collisions = json_obj["mcedit"]["collisions"]

        sprite_names.append(name)

        if (
            datas_header_path.exists()
            and json_path.stat().st_mtime < datas_header_path.stat().st_mtime
            and tools_mtime < datas_header_path.stat().st_mtime
        ):
            continue

        sprite_kind_enum_regen = True

        with open(datas_header_path, "w", encoding="utf-8") as header:
            write_source_heading(header)

            header.write("#pragma once\n\n")

            header.write('#include "gm/cfg/sprite_datas.h"\n')
            header.write('#include "gen/sprite_kind.h"\n\n')

            header.write("#include <bn_array.h>\n\n")

            header.write(f'#include "bn_sprite_items_{name}.h"\n\n')

            header.write(f"namespace {NAMESPACE}::gm::cfg::gen::priv\n")
            header.write("{\n\n")

            for frame in range(len(collisions)):
                colls = collisions[frame]

                # collision boxes
                def write_boxes(boxes_identifier: str):
                    if boxes_identifier in colls and len(colls[boxes_identifier]) > 0:
                        header.write(
                            f"inline constexpr bn::array<box_data, {len(colls[boxes_identifier])}> {name}_frame_{frame}_{boxes_identifier} {{\n"
                        )
                        for box in colls[boxes_identifier]:
                            header.write("    box_data(")
                            header.write(f'{box["x"]}, ')
                            header.write(f'{box["y"]}, ')
                            header.write(f'{box["width"]}, ')
                            header.write(f'{box["height"]}')
                            header.write("),\n")
                        header.write("};\n\n")
                    else:
                        header.write(
                            f"inline constexpr bn::span<const box_data> {name}_frame_{frame}_{boxes_identifier};\n\n"
                        )

                write_boxes("wallboxes")
                write_boxes("hurtboxes")
                write_boxes("hitboxes")

                # projectiles
                if "projectiles" in colls and len(colls["projectiles"]) > 0:
                    header.write(
                        f"inline constexpr bn::array<projectile_data, {len(colls["projectiles"])}> {name}_frame_{frame}_projectiles {{\n"
                    )
                    for proj in colls["projectiles"]:
                        header.write("    projectile_data(")
                        header.write(f'projectile_kind::{proj["kind"]}, ')
                        header.write(f'{proj["x"]}, ')
                        header.write(f'{proj["y"]}, ')
                        header.write(f'direction::{proj["direction"]}, ')
                        header.write(f'{proj["speed"]}')
                        header.write("),\n")
                    header.write("};\n\n")
                else:
                    header.write(
                        f"inline constexpr bn::span<const projectile_data> {name}_frame_{frame}_projectiles;\n\n"
                    )

            # sprite_frame_datas
            if len(collisions) > 0:
                header.write(
                    f"inline constexpr bn::array<sprite_frame_datas, {len(collisions)}> {name}_frame_datas {{\n"
                )
                for frame in range(len(collisions)):
                    header.write(f"    sprite_frame_datas(\n")
                    header.write(f"        {name}_frame_{frame}_wallboxes, ")
                    header.write(f"{name}_frame_{frame}_hurtboxes,\n")
                    header.write(f"        {name}_frame_{frame}_hitboxes, ")
                    header.write(f"{name}_frame_{frame}_projectiles\n")
                    header.write("    ),\n")
                header.write("};\n\n")
            else:
                header.write(
                    f"inline constexpr bn::span<const sprite_frame_datas> {name}_frame_datas;\n\n"
                )

            # sprite_datas
            header.write(
                f"inline constexpr sprite_datas spr_{name}_datas(sprite_kind::{name}, bn::sprite_items::{name}, {name}_frame_datas);\n\n"
            )

            header.write(f"}} // namespace {NAMESPACE}::gm::cfg::gen::priv\n")

    if sprite_kind_enum_regen:
        enum_header_path = build_include_path.joinpath("sprite_kind.h")

        with open(enum_header_path, "w", encoding="utf-8") as header:
            write_source_heading(header)

            header.write("#pragma once\n\n")

            header.write(f"namespace {NAMESPACE}::gm::cfg::gen\n")
            header.write("{\n\n")

            header.write("enum class sprite_kind\n")
            header.write("{\n")
            for name in sprite_names:
                header.write(f"    {name},\n")
            header.write("};\n\n")

            header.write(f"}} // namespace {NAMESPACE}::gm::cfg::gen\n")

        getter_inline_header_path = build_include_path.joinpath("sprite_datas.inl")

        with open(getter_inline_header_path, "w", encoding="utf-8") as header:
            write_source_heading(header)

            header.write('#include "gm/cfg/sprite_datas.h"\n\n')

            header.write("#include <utility>\n\n")

            for name in sprite_names:
                header.write(f'#include "gen/spr_{name}.h"\n')
            header.write("\n")

            header.write(f"namespace {NAMESPACE}::gm::cfg\n")
            header.write("{\n\n")

            header.write(
                "constexpr auto sprite_datas::get(gen::sprite_kind kind) -> const sprite_datas&\n"
            )
            header.write("{\n")
            header.write("    switch (kind)\n")
            header.write("    {\n")
            for name in sprite_names:
                header.write(f"    case gen::sprite_kind::{name}:\n")
                header.write(f"        return gen::priv::spr_{name}_datas;\n")
            header.write("    default:\n")
            header.write('        BN_ERROR("Invalid sprite kind: ", (int)kind);\n')
            header.write("    }\n\n")

            header.write("    std::unreachable();\n")
            header.write("}\n\n")

            header.write(f"}} // namespace {NAMESPACE}::gm::cfg\n")


def write_datas(graphics_folder_path: Path, build_folder_path: Path):
    try:
        build_folder_path.joinpath("include/gen").mkdir(parents=True, exist_ok=True)
        build_folder_path.joinpath("src").mkdir(parents=True, exist_ok=True)

        tools_path = Path(__file__).parent
        tools_mtime = max(p.stat().st_mtime for p in tools_path.glob("*.py"))

        write_sprite_datas_sources(
            graphics_folder_path.joinpath("spr"), build_folder_path, tools_mtime
        )

    except:
        remove_built_files(build_folder_path)
        raise
